/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": "#00e380",
        "on-surface": "#dae2fd",
        "surface-container-low": "#131b2e",
        "on-secondary-container": "#ffe7dc",
        "surface-bright": "#31394d",
        "surface": "#0b1326",
        "on-tertiary-container": "#713fdb",
        "tertiary-container": "#e6d9ff",
        "secondary-fixed": "#ffdbc9",
        "tertiary": "#fffafb",
        "on-surface-variant": "#b9cbba",
        "surface-variant": "#2d3449",
        "on-tertiary": "#3c0091",
        "on-background": "#dae2fd",
        "on-secondary": "#532200",
        "on-primary": "#00391b",
        "on-error": "#690005",
        "inverse-surface": "#dae2fd",
        "on-secondary-fixed-variant": "#763300",
        "outline-variant": "#3b4b3e",
        "on-tertiary-fixed": "#23005c",
        "secondary": "#ffb68d",
        "primary-container": "#22ff92",
        "error-container": "#93000a",
        "surface-dim": "#0b1326",
        "background": "#0b1326",
        "primary-fixed": "#5dff9e",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-container-high": "#222a3d",
        "on-primary-fixed-variant": "#00522a",
        "secondary-fixed-dim": "#ffb68d",
        "inverse-primary": "#006d3a",
        "primary-fixed-dim": "#00e380",
        "secondary-container": "#ae4f00",
        "on-primary-fixed": "#00210e",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#331200",
        "error": "#ffb4ab",
        "surface-container": "#171f33",
        "tertiary-fixed-dim": "#d0bcff",
        "tertiary-fixed": "#e9ddff",
        "on-primary-container": "#00723d",
        "primary": "#f4fff2",
        "outline": "#849586",
        "inverse-on-surface": "#283044",
        "surface-container-lowest": "#060e20"
      },
      fontFamily: {
        display: ["Hanken Grotesk", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      spacing: {
        gutter: "20px",
        xs: "4px",
        md: "16px",
        "base-unit": "4px",
        "container-max": "1280px",
        lg: "24px",
        sm: "8px",
        xl: "48px"
      }
    },
  },
  plugins: [],
}
